version: '3'
services:
  # MySQL database service
  projectdb:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: yggdrasil
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: yggdrasil
      DB_DRIVER: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql-healthcheck.sh:/healthcheck.sh
      - ./docker/my.cnf:/etc/mysql/my.cnf
    healthcheck:
      test: [ 'CMD', 'bash', '/healthcheck.sh' ]

  # Node.js application service
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      projectdb:
        condition: service_healthy
    environment:
      MYSQL_HOST: projectdb
      MYSQL_PORT: 3306
      MYSQL_USER: yggdrasil
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: yggdrasil
      DB_DRIVER: mysql
    ports:
      - "4000:4000"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/api-healthcheck.sh:/healthcheck.sh
    entrypoint: ['/entrypoint.sh']
    healthcheck:
      test: [ 'CMD', 'bash', '/healthcheck.sh' ]

  # Initiate DB with the given data
  initdb:
    image: mysql:8.0
    command: ["bash", "-c", "sleep 10 && mysql -hprojectdb -uyggdrasil -ppassword yggdrasil < /docker-entrypoint-initdb.d/init.sql"]

    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    depends_on:
      api:
        condition: service_healthy

volumes:
  mysql_data:
